# Generated by Django 3.0.6 on 2020-05-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('color', models.CharField(choices=[('red', 'Red'), ('blue', 'Blue')], max_length=15)),
            ],
            options={
                'ordering': ['-order'],
            },
        ),
    ]
